// (c) Copyright HutongGames, LLC 2010-2015. All rights reserved.

namespace HutongGames.PlayMaker.Utils.Enum
{
	/// <summary>
	/// Enum class base. Base Class for enums generated by PlayMaker Enum Creator Wizard. It's used to scan a project for 
	/// generated enums, to edit and manage them.
	/// </summary>
	public class EnumClassBase : System.Object {}
}
